#!/usr/bin/env python3
"""Migrate manifest entries into chapters/, labs/, and reporting/.

Idempotent: running twice yields the same result. The For Reviewers
skeleton is appended once, gated on a fence comment.
"""
from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SIBLINGS = ROOT.parent
MANIFEST = ROOT / "_data" / "manifest.json"
LOG = ROOT / "MIGRATION_LOG.md"

# YAML keys to strip from tutorial pages (site-only)
STRIP_KEYS = {
    "format",       # tutorials site has multi-format with revealjs etc
    "execute",      # left to book-level config
    "callout-icon",
    "page-layout",
    "toc-location",
    "toc-depth",
    "toc",
    "back-to-top-navigation",
    "filters",
    "include-in-header",
    "image",
    "image-alt",
    "site-url",
    "repo-url",
}

REVIEWER_FENCE_OPEN = "<!-- BEGIN for-reviewers (auto-inserted skeleton) -->"
REVIEWER_FENCE_CLOSE = "<!-- END for-reviewers -->"

REVIEWER_SKELETON = f"""

{REVIEWER_FENCE_OPEN}

## For Reviewers

**What to look for in a paper using this method.**

- **Common misapplications.**
- **Diagnostics that should be reported but often aren't.**
- **Red flags in tables and figures.**
- **What to verify.**
- **What an adequate Methods paragraph must contain.**

<!-- TODO:reviewer-section -->

{REVIEWER_FENCE_CLOSE}
"""


def split_frontmatter(text: str) -> tuple[str, str]:
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n?", text, re.S)
    if not m:
        return "", text
    return m.group(1), text[m.end():]


def strip_yaml_keys(fm: str) -> str:
    """Drop top-level keys in STRIP_KEYS and their indented children."""
    lines = fm.splitlines()
    out: list[str] = []
    skipping = False
    for line in lines:
        if not line:
            if not skipping:
                out.append(line)
            continue
        if re.match(r"^[A-Za-z][\w\-]*:", line):
            key = line.split(":", 1)[0].strip()
            if key in STRIP_KEYS:
                skipping = True
                continue
            skipping = False
            out.append(line)
        else:
            if not skipping:
                out.append(line)
    return "\n".join(out).strip()


def transform_tutorial(text: str) -> str:
    fm, body = split_frontmatter(text)
    if fm:
        fm = strip_yaml_keys(fm)
        new = f"---\n{fm}\n---\n\n{body.lstrip()}"
    else:
        new = text
    if REVIEWER_FENCE_OPEN not in new:
        new = new.rstrip() + REVIEWER_SKELETON
    # Rewrite intra-tutorial relative links: ../<cat>/<slug>.qmd or
    # /tutorials/<cat>/<slug>.qmd → ../<chapter>/<slug>.qmd. We cannot
    # know the destination chapter cheaply here without the manifest;
    # leave the links untouched and let inject_crosslinks pass do
    # additional work later. Quarto cross-refs by file name still
    # resolve when the slug is unique within the book.
    return new


def transform_lab(text: str) -> str:
    fm, body = split_frontmatter(text)
    if fm:
        # Strip multi-format publishing junk; keep title/subtitle/date
        fm = strip_yaml_keys(fm)
        new = f"---\n{fm}\n---\n\n{body.lstrip()}"
    else:
        new = text
    return new


def main() -> None:
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    entries = data["entries"]

    log_lines: list[str] = [
        "# Migration log",
        "",
        "Generated by `scripts/migrate.py`. One row per source file.",
        "",
        "| Kind | Source | Target | Transformations |",
        "|---|---|---|---|",
    ]

    for e in entries:
        src = SIBLINGS / e["source"]
        dst = ROOT / e["target"]
        dst.parent.mkdir(parents=True, exist_ok=True)
        if not src.exists():
            print(f"[skip] missing: {src}")
            continue
        text = src.read_text(encoding="utf-8")
        if e["kind"] == "method":
            new = transform_tutorial(text)
            xforms = "strip-yaml; append-reviewer-skeleton"
        else:
            new = transform_lab(text)
            xforms = "strip-yaml"
        dst.write_text(new, encoding="utf-8")
        log_lines.append(
            f"| {e['kind']} | `{e['source']}` | `{e['target']}` | {xforms} |"
        )

    # Copy course R scripts into shared/code/<chapter>/
    code_dirs = {
        1: SIBLINGS / "courses" / "course1_foundations" / "code",
        2: SIBLINGS / "courses" / "course2_regression" / "code",
        3: SIBLINGS / "courses" / "course3_design_causal" / "code",
        4: SIBLINGS / "courses" / "course4_ml_highdim" / "code",
    }
    for course, cdir in code_dirs.items():
        if not cdir.exists():
            continue
        out = ROOT / "shared" / "code" / f"course{course}"
        out.mkdir(parents=True, exist_ok=True)
        for r in cdir.glob("*.R"):
            shutil.copy2(r, out / r.name)
            log_lines.append(
                f"| code | `{r.relative_to(SIBLINGS).as_posix()}` "
                f"| `shared/code/course{course}/{r.name}` | copy |"
            )

    # Copy shared data
    data_src = SIBLINGS / "courses" / "shared" / "data"
    data_dst = ROOT / "shared" / "data"
    if data_src.exists():
        if data_dst.exists():
            shutil.rmtree(data_dst)
        shutil.copytree(data_src, data_dst)
        log_lines.append(
            f"| data | `courses/shared/data/` | `shared/data/` | copy-tree |"
        )

    LOG.write_text("\n".join(log_lines) + "\n", encoding="utf-8")
    print(f"Migrated {len(entries)} entries; log at {LOG.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
